apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-web
  labels:
    app: fil_rouge-v2-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fil_rouge-v2-web
  template:
    metadata:
      labels:
        app: fil_rouge-v2-web
    spec:
      containers:
        - name: web
          image: kendasall/fil_rouge-v2
          ports:
            - containerPort: 80
